//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeppMailer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotRead {
            get {
                return ((bool)(this["NotRead"]));
            }
            set {
                this["NotRead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Todey {
            get {
                return ((bool)(this["Todey"]));
            }
            set {
                this["Todey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Wikly {
            get {
                return ((bool)(this["Wikly"]));
            }
            set {
                this["Wikly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool All {
            get {
                return ((bool)(this["All"]));
            }
            set {
                this["All"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int filter {
            get {
                return ((int)(this["filter"]));
            }
            set {
                this["filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int interval {
            get {
                return ((int)(this["interval"]));
            }
            set {
                this["interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeppelin/zepp/")]
        public string http_zepp {
            get {
                return ((string)(this["http_zepp"]));
            }
            set {
                this["http_zepp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Pochta_chek {
            get {
                return ((bool)(this["Pochta_chek"]));
            }
            set {
                this["Pochta_chek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=zeppelin;User Id=admin;password=scoraya911;Persist Security Info=True;data" +
            "base=zepp;Character Set=utf8")]
        public string ConectToZepp {
            get {
                return ((string)(this["ConectToZepp"]));
            }
            set {
                this["ConectToZepp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NameBrauser {
            get {
                return ((string)(this["NameBrauser"]));
            }
            set {
                this["NameBrauser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DirBrauser {
            get {
                return ((string)(this["DirBrauser"]));
            }
            set {
                this["DirBrauser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ZEPPELIN\\doc\\polnocvet")]
        public string PutchPolnocvet {
            get {
                return ((string)(this["PutchPolnocvet"]));
            }
            set {
                this["PutchPolnocvet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int renemePolnocvet {
            get {
                return ((int)(this["renemePolnocvet"]));
            }
            set {
                this["renemePolnocvet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeppelin/zepp/media/com_projectlog/docs/polnocvet/")]
        public string linkPolnocvet {
            get {
                return ((string)(this["linkPolnocvet"]));
            }
            set {
                this["linkPolnocvet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Cehcom\\хранилище 1")]
        public string _PutchPolnocvet {
            get {
                return ((string)(this["_PutchPolnocvet"]));
            }
            set {
                this["_PutchPolnocvet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://Cehcom/хранилище 1/")]
        public string _linkPolnocvet {
            get {
                return ((string)(this["_linkPolnocvet"]));
            }
            set {
                this["_linkPolnocvet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=zeppelin;User Id=admin;password=scoraya911;Persist Security Info=True;data" +
            "base=zepp;Character Set=utf8")]
        public string ццц {
            get {
                return ((string)(this["ццц"]));
            }
            set {
                this["ццц"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;User Id=root;password=;Persist Security Info=True;database=zepp;" +
            "Character Set=utf8")]
        public string qqq {
            get {
                return ((string)(this["qqq"]));
            }
            set {
                this["qqq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>000м</string>
  <string>000г</string>
  <string>010м</string>
  <string>010г</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection laminaciy {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["laminaciy"]));
            }
            set {
                this["laminaciy"] = value;
            }
        }
    }
}
